{
    "url": "https://api.github.com/repos/commons-app/apps-android-commons/issues/1581",
    "repository_url": "https://api.github.com/repos/commons-app/apps-android-commons",
    "labels_url": "https://api.github.com/repos/commons-app/apps-android-commons/issues/1581/labels{/name}",
    "comments_url": "https://api.github.com/repos/commons-app/apps-android-commons/issues/1581/comments",
    "events_url": "https://api.github.com/repos/commons-app/apps-android-commons/issues/1581/events",
    "html_url": "https://github.com/commons-app/apps-android-commons/issues/1581",
    "id": 328753165,
    "node_id": "MDU6SXNzdWUzMjg3NTMxNjU=",
    "number": 1581,
    "title": "Crash after granting permission.",
    "user": {
        "login": "TGar21",
        "id": 22919326,
        "node_id": "MDQ6VXNlcjIyOTE5MzI2",
        "avatar_url": "https://avatars.githubusercontent.com/u/22919326?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/TGar21",
        "html_url": "https://github.com/TGar21",
        "followers_url": "https://api.github.com/users/TGar21/followers",
        "following_url": "https://api.github.com/users/TGar21/following{/other_user}",
        "gists_url": "https://api.github.com/users/TGar21/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/TGar21/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/TGar21/subscriptions",
        "organizations_url": "https://api.github.com/users/TGar21/orgs",
        "repos_url": "https://api.github.com/users/TGar21/repos",
        "events_url": "https://api.github.com/users/TGar21/events{/privacy}",
        "received_events_url": "https://api.github.com/users/TGar21/received_events",
        "type": "User",
        "site_admin": false
    },
    "labels": [
        {
            "id": 257201818,
            "node_id": "MDU6TGFiZWwyNTcyMDE4MTg=",
            "url": "https://api.github.com/repos/commons-app/apps-android-commons/labels/bug",
            "name": "bug",
            "color": "fc2929",
            "default": true,
            "description": null
        },
        {
            "id": 545074708,
            "node_id": "MDU6TGFiZWw1NDUwNzQ3MDg=",
            "url": "https://api.github.com/repos/commons-app/apps-android-commons/labels/high%20priority",
            "name": "high priority",
            "color": "ff23f7",
            "default": false,
            "description": null
        }
    ],
    "state": "closed",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": null,
    "comments": 4,
    "created_at": "2018-06-02T15:32:57Z",
    "updated_at": "2018-11-03T12:43:33Z",
    "closed_at": "2018-11-03T12:42:50Z",
    "author_association": "NONE",
    "active_lock_reason": null,
    "body": "**Summary:** \r\nCommons crashing during granting a Location permission aftr first run. I am using Oreo device.\r\nSee the video: https://www.dropbox.com/s/3aig57i1x6pdcok/2018_06_02_17_20_08.mp4?dl=0\r\n\r\n**Steps to reproduce:** \r\n\r\n1. Turn off the GPS permission\r\n2. Clear data\r\n3. Start app\r\n4. Go through the onboarding and sign in\r\n5. Press menu icon and choose Nearby option\r\n6. Dialogue asking for GPS permission appears, confirm it\r\n7. Add the permission in the settings and then in the dialogue\r\n\r\n\r\nHow can we reproduce the issue?\r\n`06-02 12:44:46.199 12044 12044 E AndroidRuntime: FATAL EXCEPTION: main 06-02 12:44:46.199 12044 12044 E AndroidRuntime: Process: fr.free.nrw.commons, PID: 12044 06-02 12:44:46.199 12044 12044 E AndroidRuntime: java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=1, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {fr.free.nrw.commons/fr.free.nrw.commons.nearby.NearbyActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'double android.location.Location.getLatitude()' on a null object reference 06-02 12:44:46.199 12044 12044 E AndroidRuntime: at android.app.ActivityThread.deliverResults(ActivityThread.java:4581) 06-02 12:44:46.199 12044 12044 E AndroidRuntime: at android.app.ActivityThread.handleSendResult(ActivityThread.java:4631) 06-02 12:44:46.199 12044 12044 E AndroidRuntime: at android.app.ActivityThread.-wrap19(Unknown Source:0) 06-02 12:44:46.199 12044 12044 E AndroidRuntime: at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1699) 06-02 12:44:46.199 12044 12044 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:105) 06-02 12:44:46.199 12044 12044 E AndroidRuntime: at android.os.Looper.loop(Looper.java:180) 06-02 12:44:46.199 12044 12044 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:6944) 06-02 12:44:46.199 12044 12044 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method) 06-02 12:44:46.199 12044 12044 E AndroidRuntime: at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 06-02 12:44:46.199 12044 12044 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:835) 06-02 12:44:46.199 12044 12044 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'double android.location.Location.getLatitude()' on a null object reference 06-02 12:44:46.199 12044 12044 E AndroidRuntime: at fr.free.nrw.commons.location.LatLng.from(LatLng.java:45) 06-02 12:44:46.199 12044 12044 E AndroidRuntime: at fr.free.nrw.commons.location.LocationServiceManager.getLKL(LocationServiceManager.java:93) 06-02 12:44:46.199 12044 12044 E AndroidRuntime: at fr.free.nrw.commons.nearby.NearbyActivity.onRequestPermissionsResult(NearbyActivity.java:163) 06-02 12:44:46.199 12044 12044 E AndroidRuntime: at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:7399) 06-02 12:44:46.199 12044 12044 E AndroidRuntime: at android.app.Activity.dispatchActivityResult(Activity.java:7250) 06-02 12:44:46.199 12044 12044 E AndroidRuntime: at android.app.ActivityThread.deliverResults(ActivityThread.java:4577) 06-02 12:44:46.199 12044 12044 E AndroidRuntime: ... 9 more`\r\n\r\n**Expected behavior:** \r\nIt should show the map.\r\n\r\n**Observed behavior:** \r\nCrash. After returning to the app again, the map is shown normally.\r\n\r\n**Device and Android version:** \r\nHTC 10, OS 8.0.0 Oreo, stock version\r\n \r\n **Commons app version:** \r\n2.7.1. downloaded from Play store\r\n\r\n**Video:** \r\n\r\nhttps://www.dropbox.com/s/3aig57i1x6pdcok/2018_06_02_17_20_08.mp4?dl=0\r\n\r\n**Would you like to work on the issue?**\r\n\r\nI would like to look at it. If I won't manage to fix this, I'll let you know.\r\n",
    "closed_by": {
        "login": "domdomegg",
        "id": 4953590,
        "node_id": "MDQ6VXNlcjQ5NTM1OTA=",
        "avatar_url": "https://avatars.githubusercontent.com/u/4953590?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/domdomegg",
        "html_url": "https://github.com/domdomegg",
        "followers_url": "https://api.github.com/users/domdomegg/followers",
        "following_url": "https://api.github.com/users/domdomegg/following{/other_user}",
        "gists_url": "https://api.github.com/users/domdomegg/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/domdomegg/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/domdomegg/subscriptions",
        "organizations_url": "https://api.github.com/users/domdomegg/orgs",
        "repos_url": "https://api.github.com/users/domdomegg/repos",
        "events_url": "https://api.github.com/users/domdomegg/events{/privacy}",
        "received_events_url": "https://api.github.com/users/domdomegg/received_events",
        "type": "User",
        "site_admin": false
    },
    "reactions": {
        "url": "https://api.github.com/repos/commons-app/apps-android-commons/issues/1581/reactions",
        "total_count": 0,
        "+1": 0,
        "-1": 0,
        "laugh": 0,
        "hooray": 0,
        "confused": 0,
        "heart": 0,
        "rocket": 0,
        "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/commons-app/apps-android-commons/issues/1581/timeline",
    "performed_via_github_app": null,
    "state_reason": "completed"
}