{
    "url": "https://api.github.com/repos/PhenoApps/Field-Book/issues/540",
    "repository_url": "https://api.github.com/repos/PhenoApps/Field-Book",
    "labels_url": "https://api.github.com/repos/PhenoApps/Field-Book/issues/540/labels{/name}",
    "comments_url": "https://api.github.com/repos/PhenoApps/Field-Book/issues/540/comments",
    "events_url": "https://api.github.com/repos/PhenoApps/Field-Book/issues/540/events",
    "html_url": "https://github.com/PhenoApps/Field-Book/issues/540",
    "id": 1623929219,
    "node_id": "I_kwDOATAHC85gyzGD",
    "number": 540,
    "title": "Not able to import fields to the app [BUG]",
    "user": {
        "login": "bangira",
        "id": 92544145,
        "node_id": "U_kgDOBYQckQ",
        "avatar_url": "https://avatars.githubusercontent.com/u/92544145?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/bangira",
        "html_url": "https://github.com/bangira",
        "followers_url": "https://api.github.com/users/bangira/followers",
        "following_url": "https://api.github.com/users/bangira/following{/other_user}",
        "gists_url": "https://api.github.com/users/bangira/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/bangira/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/bangira/subscriptions",
        "organizations_url": "https://api.github.com/users/bangira/orgs",
        "repos_url": "https://api.github.com/users/bangira/repos",
        "events_url": "https://api.github.com/users/bangira/events{/privacy}",
        "received_events_url": "https://api.github.com/users/bangira/received_events",
        "type": "User",
        "site_admin": false
    },
    "labels": [
        {
            "id": 100533894,
            "node_id": "MDU6TGFiZWwxMDA1MzM4OTQ=",
            "url": "https://api.github.com/repos/PhenoApps/Field-Book/labels/bug",
            "name": "bug",
            "color": "fc2929",
            "default": true,
            "description": null
        }
    ],
    "state": "closed",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": null,
    "comments": 4,
    "created_at": "2023-03-14T17:01:17Z",
    "updated_at": "2023-03-14T21:02:23Z",
    "closed_at": "2023-03-14T21:02:23Z",
    "author_association": "NONE",
    "active_lock_reason": null,
    "body": "**Describe the bug**\r\nI am not able to import fields to the fieldbook app. We export the fieldbook from Breedbase and put them on onedrive cloud and then import them to the app. We followed the same process last year (2022) and it worked but this year with version 5.3.0 it is not importing fields.   \r\n\r\n**To Reproduce**\r\nSteps to reproduce the behavior:\r\n1. Go to 'fieldbook app'\r\n2. Click on 'click on fields'\r\n3. Click on  'three dots and click import'\r\n4. Select cloud, go to onedrive or any cloud service\r\n5. click on field \r\n6. and it brings you back to the filedbook app but nothing imports \r\n\r\n**Expected behavior**\r\n\r\nWhen I click on the field from cloud, it should give me option to select primary and secondary identifier and then import the field\r\n\r\n**video**\r\nhttps://user-images.githubusercontent.com/92544145/225080482-1112d656-7ac5-4fa8-a0b3-1841383e4446.mp4\r\n\r\n\r\n**Device Info (please complete the following information):**\r\n - Model: [Motorola one 5G Ace ]\r\n - OS: [e.g. Android 10]\r\n - Field Book Version [5.3.0]\r\n\r\n**Additional context**\r\nWe are setting up the phones for this growing season, so please help us",
    "closed_by": {
        "login": "trife",
        "id": 1869534,
        "node_id": "MDQ6VXNlcjE4Njk1MzQ=",
        "avatar_url": "https://avatars.githubusercontent.com/u/1869534?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/trife",
        "html_url": "https://github.com/trife",
        "followers_url": "https://api.github.com/users/trife/followers",
        "following_url": "https://api.github.com/users/trife/following{/other_user}",
        "gists_url": "https://api.github.com/users/trife/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/trife/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/trife/subscriptions",
        "organizations_url": "https://api.github.com/users/trife/orgs",
        "repos_url": "https://api.github.com/users/trife/repos",
        "events_url": "https://api.github.com/users/trife/events{/privacy}",
        "received_events_url": "https://api.github.com/users/trife/received_events",
        "type": "User",
        "site_admin": false
    },
    "reactions": {
        "url": "https://api.github.com/repos/PhenoApps/Field-Book/issues/540/reactions",
        "total_count": 0,
        "+1": 0,
        "-1": 0,
        "laugh": 0,
        "hooray": 0,
        "confused": 0,
        "heart": 0,
        "rocket": 0,
        "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/PhenoApps/Field-Book/issues/540/timeline",
    "performed_via_github_app": null,
    "state_reason": "completed"
}